config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', to: 'application#simulation', as: 'simulation'
  get '/componentes', to: 'application#componentes', as: 'componentes'
  get '/energia_renovable', to: 'application#energia_renovable', as: 'info_energia'
  get '/marco_teorico', to: 'application#marco_teorico', as: 'marco_teorico'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def simulation
        if params[:velocidad_entrada]
            @velocidad_entrada = params[:velocidad_entrada].to_f
        else
            @velocidad_entrada = 0
        end
        if params[:velocidad_salida]
            @velocidad_salida = params[:velocidad_salida].to_f
        else
            @velocidad_salida = 0
        end
        if params[:largo_aspa]
            @largo_aspa = params[:largo_aspa].to_i
        else
            @largo_aspa = 0
        end
        

        if @velocidad_entrada == 0 && @velocidad_salida == 0
            @factor_induccion = 0
        else
            @factor_induccion = (@velocidad_entrada - @velocidad_salida)/@velocidad_salida
        end

        if @velocidad_entrada < @velocidad_salida
            @potencia = 0
            @factor_induccion = 0
        else
            @potencia = 0.5 * 1.1839 * (3.141592653589793238462643313830947690870926 * @largo_aspa * @largo_aspa) * (@velocidad_entrada * @velocidad_entrada * @velocidad_entrada) * ((4 * @factor_induccion) * (1 - @factor_induccion) * (1 - @factor_induccion))
        end
        

        @coeficiente_potencia = (4 * @factor_induccion) * (1 - @factor_induccion)


        @coeficientes = [@factor_induccion, @potencia, @coeficiente_potencia]
        respond_to do |format|
            format.html
            format.js
        end
    end

    def componentes
        
    end

    def energia_renovable
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_coeficiente.html.erb
<div class="card carta-resultados">
    <div class="card-header">
        Simulacion
    </div>
    <div class="card-body">
        <%if (@coeficientes[0] == 0)%>
                    <div style="width:100%;height:0;padding-bottom:67%;position:relative;"><img src="https://energia-eolica.s3-sa-east-1.amazonaws.com/inicial1.png" width="90%" height="100%" style="position:absolute" frameBorder="0"  allowFullScreen></img></div>
        <%else%>
            <%if (@velocidad_entrada <=4 )%>
                <div style="width:100%;height:100%;padding-bottom:67%;position:relative;"><iframe src="https://energia-eolica.s3-sa-east-1.amazonaws.com/gif1.gif" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div>
            <%end%>        

            <%if ((@velocidad_entrada > 4) and (@velocidad_entrada <= 6))%>
                <div style="width:100%;height:0;padding-bottom:67%;position:relative;"><iframe src="https://energia-eolica.s3-sa-east-1.amazonaws.com/gif2.gif" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div>
            <%end%>

            <%if ((@velocidad_entrada > 6) and (@velocidad_entrada <= 8))%>
                <div style="width:100%;height:0;padding-bottom:67%;position:relative;"><iframe src="https://energia-eolica.s3-sa-east-1.amazonaws.com/gif3.gif" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div>
            <%end%>

            <%if ((@velocidad_entrada > 8) and (@velocidad_entrada <= 10))%>
                <div style="width:100%;height:0;padding-bottom:67%;position:relative;"><iframe src="https://energia-eolica.s3-sa-east-1.amazonaws.com/gif4.gif" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div>
            <%end%>

            <%if (@velocidad_entrada > 10 )%>
                <div style="width:100%;height:0;padding-bottom:67%;position:relative;"><iframe src="https://energia-eolica.s3-sa-east-1.amazonaws.com/gif5.gif" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div>
            <%end%>

        <%end%>
    </div>
</div>


<div class="card carta-resultados">
    <div class="card-header">
        Resultados
    </div>
    <div class="card-body">
        <%if (@velocidad_entrada < @velocidad_salida )%>
            <p class="card-text"><strong>Error. La velocidad de entrada del viento a la turbina debe ser mayor a la velocidad de salida del viento.</strong></p>
        <%else%>
            <p class="card-text"><strong>Factor de induccion:</strong> <%= @coeficientes[0].round(5) %></p>
            <p class="card-text"><strong>Potencia:</strong> <%= @coeficientes[1].round(2) %> W</p>
            <p class="card-text"><strong>Coeficiente de potencia:</strong> <%= @coeficientes[2].round(5) %></p>
        <%end%>

    </div>
</div>
<br>
<br>
<br>
<br>
<br>

app/views/application/componentes.html.erb
<!DOCTYPE html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>

  <body>
    <div class="container container-simulacion">
        <div class="row">
          <div class="col">
            <div class="card carta-componentes">
                <div class="card-header">
                    Componentes
                </div>
                <div class="card-body">
                    <div style="width:100%;height:0;padding-bottom:69%;position:relative;"><iframe src="https://giphy.com/embed/Gl6hONXZ1wJHO" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/wind-turbines-windturbines-Gl6hONXZ1wJHO">via GIPHY</a></p>
            
                </div>
            </div>
          </div>
        </div>
    </div>
    <div class="container container-simulacion">
        <div class="row">
          <div class="col">
            <div class="card carta-componentes">
                <div class="card-header">
                    Las turbinas
                </div>
                <div class="card-body">
                    <figure>
                        <p>Las turbinas son máquinas motrices de flujo continuo que producen trabajo mecánico mediante un sistema de alabes de formas diversas empleando la energía cinética, térmica o de presión de un fluido (MOTORGIGA, 2016).
                           Existen varios tipos de turbinas, las más conocidas son la hidráulica ( accionadas por agua) y la eólica (accionada por el viento).</p>
                        <img class="img-energia" src="https://media.elmostrador.cl/2016/11/parque-eolico-700x467.jpg" alt="ilustracion energia renovable">

                        <p>Los fluidos pasan a través de estas turbinas, produciendo un giro en las aspas de esta, este giro hace que comience a funcionar el motor donde se va a transformar la energía hidráulica o la eólica en energía mecánica, y así por ejemplo se puede generar electricidad.
                             Entonces es muy importante destacar que este sistema depende fundamentalmente del fluido que pase por este.</p>

                        <p>Lo que hace que este mecanismo funcione, es el viento. El flujo de aire que pasa a través de las palas hace que se genere un gradiente de presiones entre ambas caras, este gradiente da origen a una Fuerza que actúa sobre la pala y hace que gire.
                          Los aerogeneradores transforman la energía cinética del viento (generada por el movimiento de las palas) en energía mecánica, aquí se aplican las leyes de conservación de momento, masa y energía.</p>
                    </figure>
            
                </div>
            </div>
          </div>
        </div>
    </div>
      
  </body>
</html>

app/views/application/energia_renovable.html.erb
<!DOCTYPE html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>

  <body>
    <div class="container container-simulacion">
        <div class="row">
          <div class="col">
            <div class="card carta-componentes">
                <div class="card-header">
                    Porque son importantes las Energias Renovables?
                </div>
                <div class="card-body">
                    <figure>
                        <img class="img-energia" src="https://www.factorenergia.com/wp-content/uploads/2018/08/energias-renovables.jpg" alt="ilustracion energia renovable">
                        <p><strong>1.- La energía renovable lucha directamente contra el cambio climático.</strong><br>
                        Ayudan a disminuir la emisión de dióxido de carbono, y otros gases que contribuyen a un «efecto invernadero».
                        </p><br>
                        
                        <p><strong>2.- La generación de energía renovable contribuye a un aire puro y a reducir la contaminación.</strong><br>
                        No se produce combustión y, por tanto, no se emiten gases dañinos para nuestra salud.
                        </p><br>
                        
                        <p><strong>3.- La energía renovable mantiene intactos los recursos del planeta.</strong><br>
                        Se aprovechan recursos renovables y que son infinitos.
                        </p><br>
                        
                        <p><strong>4.- La energía renovable contribuye a una mejor calidad de vida.</strong><br>
                        Con un impacto medioambiental mínimo, una mejor calidad del aire y una reducción de las enfermedades, la energía renovable produce una mejor calidad de vida.
                        </p><br><br><br>

                        <a href="https://www.energyavm.es/importante-la-energia-renovable">Fuente</a>

                    </figure>
            
                </div>
            </div>
          </div>
        </div>
    </div>
  </body>
</html>

app/views/application/marco_teorico.erb
<!DOCTYPE html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>

  <body>
    <div class="container container-simulacion">
        <div class="row">
          <div class="col">
            <div class="card carta-componentes">
                <div class="card-header">
                  Como funcionan las turbinas eolicas?
                </div>
                <div class="card-body">
                    <figure>
                      <p>Para comprender mejor el funcionamiento de las turbinas eólicas, tenemos que
                      saber qué es un fluido y cuáles son sus propiedades. Según Bonifacio, <strong>“Fluido es
                      una sustancia que se deforma continuamente, o sea escurre, cuando está sometido
                      a un esfuerzo de corte o tangencial”.</strong> </p>


                        <p><strong>Las reacciones de los distintos materiales están dadas por un esfuerzo de
                        corte, el cual es producido por su propio peso al no tener resistencia con el borde
                        del recipiente</strong>. En el caso de los fluidos, el esfuerzo de corte está dado por la
                        <strong> viscosidad del fluido</strong>, la cual es una de las propiedades más importantes que poseen
                        los fluidos y que se puede definir como <strong>la resistencia que opone un fluido a
                        deformarse continuamente cuando es sometida a un esfuerzo de corte.</strong></p><br>
                        
                        
                        <img class="img-energia" src="https://www.worldenergytrade.com/images/stories/news/energias_alternativas/energia_eolica/7512/tamano-turbinas-eolicas-sigue-creciendo-medida-continua-consolidacion-industria-7512.jpg" alt="ilustracion parque eolico">
                        
                        
                        <p><strong>Las turbinas</strong> son máquinas motrices de flujo continuo que producen trabajo
                        mecánico mediante un sistema de alabes de formas diversas empleando la energía
                        cinética, térmica o de presión de un fluido (MOTORGIGA, 2016). Existen varios tipos
                        de turbinas, las más conocidas son la hidráulica (accionadas por agua) y la eólica
                        (accionada por el viento).</p><br>

                        <p><strong> Los fluidos</strong> pasan a través de estas turbinas, produciendo un giro en las aspas de
                        esta, este giro hace que comience a funcionar el motor donde se va a transformar la
                        energía hidráulica o la eólica <strong>en energía mecánica</strong>, y así por ejemplo se puede
                        generar electricidad.</strong> Entonces es muy importante destacar que este sistema
                        depende fundamentalmente del fluido que pase por este.</p><br>
                        
                        <img class="img-energia" src="https://www.areatecnologia.com/electricidad/imagenes/generador-eolico.jpg" alt="ilustracion generador">

                        <p>Lo que hace que este mecanismo funcione, es el viento. <strong> El flujo de aire</strong> que pasa a
                        través de las palas hace que se <strong>genere un gradiente de presiones</strong> entre ambas
                        caras, este gradiente da <strong>origen a una Fuerza</strong> que actúa sobre la pala y hace que
                        gire. Los aerogeneradores <strong>transforman la energía cinética del viento (generada por
                        el movimiento de las palas) en energía mecánica</strong>, aquí se aplican las leyes de
                        conservación de momento, masa y energía. </p><br>
                        
                        
                        <p>Las turbinas eólicas logran convertir en energía mecánica como <strong>máximo un 59,26%</strong> de la energía cinética del viento que incide sobre ella,
                         esto según el estudio que hizo el alemán Alfred Betz. Este modelo es útil para establecer un límite superior para el Cp.
                        Pero en la realidad, <strong>los mejores diseños no han logrado llegar a ese porcentaje, están muy cerca, con un Cp entre 42-48.</strong>
                        Es por esta razón que es muy importante seguir investigando en el tema para aprovechar al máximo esta energía renovable, y así dejar de usar combustibles fósiles.</p>


                    </figure>
            
                </div>
            </div>
          </div>
        </div>
    </div>
  </body>
</html>

app/views/application/simulation.html.erb
<!DOCTYPE html>
  <head>
    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>

  <body>
    <div class="container container-simulacion">
      <div class="row">
        <div class="col">
          <div id="parametros">
            <%= render 'coeficiente', coeficientes: @coeficientes %>
          </div>
        </div>
        <div class="col">


          
        <div class="form-sliders">
          <%= form_tag(simulation_path, method: 'GET', remote: true, class: 'form_busqueda') do %>
            <%= label_tag(:velocidad_entrada, "Ingrese velocidad de entrada del viento:") %>
            <input type="range" id="velocidad_entrada" name="velocidad_entrada" min="3.5" max="11" step="0.5" onchange="updateVelocidadInicial(this.value);">
            <input type="text" id="velocidad_inicial" value="">
            <br>

            <%= label_tag(:velocidad_salida, "Ingrese velocidad de salida del viento:") %>
            <input type="range" id="velocidad_salida" name="velocidad_salida" min="3.5" max="11" step="0.5" onchange="updateVelocidadFinal(this.value);">
            <input type="text" id="velocidad_final" value="">
            <br>

            <%= label_tag(:largo_aspa, "Ingrese el largo de las aspas:") %>
            <input type="range" id="largo_aspa" name="largo_aspa" min="15" max="25" onchange="updateLargoAspa(this.value);">
            <input type="text" id="largo_inicial" value="">
            <br>

            <br>
            <%#submit_tag("Calcular", class: 'btn btn-success')%>
            <%= link_to 'Reiniciar', simulation_path, class: 'btn btn-dark' %>

          <% end %>
          </div>
        </div>
      </div>
        <div class="row">
          <div class="col">
            <div class="card carta-componentes">
                <div class="card-header">
                     Formulas utilizadas:
                </div>
                <div class="card-body">
                    <figure>
                        <p>Factor induccion<br><img class="img-energia" src="https://energia-eolica.s3-sa-east-1.amazonaws.com/factor_induccion.jpeg" alt="ilustracion energia renovable"></p>
                        <p>Coeficiente de Potencia<br><img class="img-energia" src="https://energia-eolica.s3-sa-east-1.amazonaws.com/coeficiente_potencia.jpeg" alt="ilustracion energia renovable"></p>
                        <p>Potencia<br><img class="img-energia" src="https://energia-eolica.s3-sa-east-1.amazonaws.com/potencia.jpeg" alt="ilustracion energia renovable"></p>
                        <br><br>
                        <p>Donde:<br>
                        V1 -> velocidad de entrada<br>
                        V2 -> velocidad de salida<br>
                        A2 -> Area que recorren las aspas<br>
                        p -> Densidad del aire <br>
                        </p>
                    </figure>
            
                </div>
            </div>
          </div>
        </div>
       

  </div>
    
    
  </body>
</html>
<script>
  function updateVelocidadInicial(val) {
          document.getElementById('velocidad_inicial').value=val + ' m/s';
          
        }

  function updateVelocidadFinal(val) {
          document.getElementById('velocidad_final').value=val + ' m/s'; 

        }

  function updateLargoAspa(val) {
          document.getElementById('largo_inicial').value=val + ' m'; 
        }

  // function updatePresionFinal(val) {
  //         document.getElementById('presion_final').value=val; 
  //       }
</script>

<script type="text/javascript">
  var sliders = document.querySelectorAll("input");
  var form = document.querySelector('form');

  for (const slider of sliders) {
  slider.addEventListener( 'change', function() {
    Rails.fire(form, 'submit');
  });
  }
</script>

app/views/application/simulation.js.erb
function updateCoeficientes (innerHTML) {
    const coeficientes = document.getElementById('parametros');
    coeficientes.innerHTML = innerHTML;
}
updateCoeficientes("<%= j render 'coeficiente', coeficientes: @coeficientes %>");

app/views/layouts/_footer.html.erb
<!-- Footer -->

<footer class="page-footer font-small unique-color-dark">


  <!-- Footer Links -->
  <div class="container text-center text-md-left mt-5">

    <!-- Grid row -->
    <div class="row mt-3">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">

        <!-- Content -->
        <h6 class="text-uppercase font-weight-bold"> Mecanica de Fluidos 2020-2</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <h6 class="text-uppercase ">Grupo 52</h6>


      </div>
      <!-- Grid column -->

      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Integrantes</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        
        <p>Nicolas Errazuriz</p>
        <p>Cristobal Guerrero</p>
        <p>Roberto Izquierdo</p>
        <p>Santiago Molina</p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Repositorio</h6>
        <hr class="deep-purple accent-2 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
</i> <a href="https://github.com/Iamchotiado/energia-eolica">Github</a></p>



      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->



</footer>
<!-- Footer -->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Energia Eolica</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <% if current_page?(simulation_path) %>
                <a class="nav-link active" href="#">Simulación  <span class="sr-only">(current)</span></a>
            <% else %>
                <%= link_to 'Simulacion', simulation_path, class: 'nav-link' %>
            <% end %>
            <% if current_page?(componentes_path) %>
                <a class="nav-link active" href="#">Partes de la turbina   <span class="sr-only">(current)</span></a>
            <% else %>
                <%= link_to 'Partes de la turbina', componentes_path, class: 'nav-link' %>
            <% end %>
            <% if current_page?(info_energia_path) %>
                <a class="nav-link active" href="#">Energia Renovable   <span class="sr-only">(current)</span></a>
            <% else %>
                <%= link_to 'Energia Renovable', info_energia_path, class: 'nav-link' %>
            <% end %>
            <% if current_page?(marco_teorico_path) %>
            <a class="nav-link active" href="#">Como funciona? <span class="sr-only">(current)</span></a>
        <% else %>
            <%= link_to 'Como funciona?', marco_teorico_path, class: 'nav-link' %>
        <% end %>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EnergiaEolica</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Mukta:300,400,700">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= yield %>
    <%= render 'layouts/footer'%>

    <!-- Optional JavaScript -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>